-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2022-09-13 23:36:58 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

-- Group member names: Joshua Jaden, Ria Kalachetty, Prithviram Prabhuram 
--Unit Code: FIT3171
--Applied Class No: 01

SET ECHO ON
SPOOL monh_schema_output.txt

DROP TABLE customer CASCADE CONSTRAINTS;

DROP TABLE employee CASCADE CONSTRAINTS;

DROP TABLE job CASCADE CONSTRAINTS;

DROP TABLE purpose CASCADE CONSTRAINTS;

DROP TABLE quote CASCADE CONSTRAINTS;

DROP TABLE trailer CASCADE CONSTRAINTS;

DROP TABLE trailer_class CASCADE CONSTRAINTS;

DROP TABLE trailer_type CASCADE CONSTRAINTS;

DROP TABLE truck CASCADE CONSTRAINTS;

DROP TABLE truck_class CASCADE CONSTRAINTS;

DROP TABLE truck_trail_combo CASCADE CONSTRAINTS;

DROP TABLE truck_type CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE customer (
    cust_no         CHAR(6) NOT NULL,
    cust_fam_name   VARCHAR2(30) NOT NULL,
    cust_given_name VARCHAR2(30) NOT NULL,
    cust_buss_name  VARCHAR2(30) NOT NULL,
    cust_address    VARCHAR2(50) NOT NULL,
    cust_contact_no CHAR(10) NOT NULL
);

COMMENT ON COLUMN customer.cust_no IS
    'customer number';

COMMENT ON COLUMN customer.cust_fam_name IS
    'customer family name';

COMMENT ON COLUMN customer.cust_given_name IS
    'customer given name';

COMMENT ON COLUMN customer.cust_buss_name IS
    'customer business name';

COMMENT ON COLUMN customer.cust_address IS
    'customer address';

COMMENT ON COLUMN customer.cust_contact_no IS
    'customer contact number';

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( cust_no );

CREATE TABLE employee (
    emp_no                CHAR(6) NOT NULL,
    emp_role              CHAR(1) NOT NULL,
    emp_contact_no        CHAR(10) NOT NULL,
    emp_tax_file_no       CHAR(9) NOT NULL,
    emp_salary            NUMBER(8, 2) NOT NULL,
    emp_driver_license_no CHAR(10) NOT NULL,
    emp_driver_level      CHAR(1) NOT NULL,
    emp_no1               CHAR(6),
    emp_given_name        VARCHAR2(30) NOT NULL,
    emp_fam_name          VARCHAR2(30) NOT NULL
);

ALTER TABLE employee
    ADD CONSTRAINT roles CHECK ( emp_role IN ( 'C', 'D', 'G', 'H', 'M' ) );

ALTER TABLE employee
    ADD CHECK ( emp_salary BETWEEN 1 AND 999999.99 );

ALTER TABLE employee
    ADD CONSTRAINT driver_class_level CHECK ( emp_driver_level IN ( '1', '2', '3' ) );

COMMENT ON COLUMN employee.emp_no IS
    'employee number';

COMMENT ON COLUMN employee.emp_role IS
    'employee role (M:  manger, H: mechanic, C: clerk, G:general, D: driver) ';

COMMENT ON COLUMN employee.emp_contact_no IS
    'employee contact number';

COMMENT ON COLUMN employee.emp_tax_file_no IS
    'employee tax file number';

COMMENT ON COLUMN employee.emp_salary IS
    'employee salary ';

COMMENT ON COLUMN employee.emp_driver_license_no IS
    'employee driver license number';

COMMENT ON COLUMN employee.emp_driver_level IS
    'employee driver level';

COMMENT ON COLUMN employee.emp_no1 IS
    'employee number';

COMMENT ON COLUMN employee.emp_given_name IS
    'employee given name';

COMMENT ON COLUMN employee.emp_fam_name IS
    'employee last name';

ALTER TABLE employee ADD CONSTRAINT employee_pk PRIMARY KEY ( emp_no );

CREATE TABLE job (
    job_no                  CHAR(4) NOT NULL,
    quote_prepared          DATE NOT NULL,
    quote_days_req          NUMBER(2) NOT NULL,
    quote_cost              NUMBER(7, 2) NOT NULL,
    job_pickup_dt           DATE NOT NULL,
    job_intended_dropoff_dt DATE NOT NULL,
    job_actual_dropoff_dt   DATE NOT NULL,
    job_cost                NUMBER(7, 2),
    job_paid_date           DATE NOT NULL,
    quote_no                CHAR(4) NOT NULL,
    truck_trail_no          CHAR(5) NOT NULL,
    emp_no                  CHAR(6) NOT NULL,
    emp_no1                 CHAR(6) NOT NULL
);

COMMENT ON COLUMN job.job_no IS
    'job number';

COMMENT ON COLUMN job.quote_prepared IS
    'date the quote was prepared';

COMMENT ON COLUMN job.quote_days_req IS
    'quote number of days';

COMMENT ON COLUMN job.quote_cost IS
    'quote cost';

COMMENT ON COLUMN job.job_pickup_dt IS
    'job pickup date and time';

COMMENT ON COLUMN job.job_intended_dropoff_dt IS
    'job intended dropoff date and time';

COMMENT ON COLUMN job.job_actual_dropoff_dt IS
    'job actual dropoff date and time';

COMMENT ON COLUMN job.job_cost IS
    'job cost (if actual cost is different to quoted cost)';

COMMENT ON COLUMN job.job_paid_date IS
    'date the job was paid';

COMMENT ON COLUMN job.quote_no IS
    'quote  number';

COMMENT ON COLUMN job.truck_trail_no IS
    'surrogate key for TRUCK_TRAIL_COMBO';

COMMENT ON COLUMN job.emp_no IS
    'employee number';

COMMENT ON COLUMN job.emp_no1 IS
    'employee number';

CREATE UNIQUE INDEX job__idx ON
    job (
        quote_no
    ASC );

ALTER TABLE job ADD CONSTRAINT job_pk PRIMARY KEY ( job_no );

CREATE TABLE purpose (
    purpose_no   CHAR(3) NOT NULL,
    purpose_desc VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN purpose.purpose_no IS
    'purpose number';

COMMENT ON COLUMN purpose.purpose_desc IS
    'purpose description';

ALTER TABLE purpose ADD CONSTRAINT purpose_pk PRIMARY KEY ( purpose_no );

CREATE TABLE quote (
    quote_no                 CHAR(4) NOT NULL,
    quote_booking_start_date DATE NOT NULL,
    quote_pickup_location    VARCHAR2(50) NOT NULL,
    quote_dropoff_location   VARCHAR2(50) NOT NULL,
    quote_purpose            VARCHAR2(50) NOT NULL,
    quote_cost               NUMBER(7, 2) NOT NULL,
    quote_initiated_date     DATE NOT NULL,
    quote_status             CHAR(1) NOT NULL,
    cust_no                  CHAR(6) NOT NULL,
    emp_no                   CHAR(6) NOT NULL
);

ALTER TABLE quote
    ADD CONSTRAINT quote_number_range CHECK ( quote_no BETWEEN '1000' AND '9999' );

ALTER TABLE quote
    ADD CONSTRAINT quote_costs CHECK ( quote_cost BETWEEN 1 AND 9999.99 );

ALTER TABLE quote
    ADD CONSTRAINT quote_status CHECK ( quote_status IN ( 'F', 'U' ) );

COMMENT ON COLUMN quote.quote_no IS
    'quote  number';

COMMENT ON COLUMN quote.quote_booking_start_date IS
    'quote booking start date';

COMMENT ON COLUMN quote.quote_pickup_location IS
    'quote pickup location';

COMMENT ON COLUMN quote.quote_dropoff_location IS
    'quote dropoff location';

COMMENT ON COLUMN quote.quote_purpose IS
    'quote purpose';

COMMENT ON COLUMN quote.quote_cost IS
    'quote cost';

COMMENT ON COLUMN quote.quote_initiated_date IS
    'quote initiated date';

COMMENT ON COLUMN quote.quote_status IS
    'quote status (filled or unfullfilled)';

COMMENT ON COLUMN quote.cust_no IS
    'customer number';

COMMENT ON COLUMN quote.emp_no IS
    'employee number';

ALTER TABLE quote ADD CONSTRAINT quote_pk PRIMARY KEY ( quote_no );

CREATE TABLE trailer (
    trail_code         CHAR(5) NOT NULL,
    trail_class        VARCHAR2(5) NOT NULL,
    trail_load_cap     NUMBER(5) NOT NULL,
    trail_purch_date   DATE NOT NULL,
    trail_cost         NUMBER(8, 2) NOT NULL,
    trail_len          NUMBER(3, 2) NOT NULL,
    trail_width        NUMBER(3, 2) NOT NULL,
    trail_model        VARCHAR2(30) NOT NULL,
    trail_manufacturer VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN trailer.trail_code IS
    'trailer code';

COMMENT ON COLUMN trailer.trail_class IS
    'trailer class';

COMMENT ON COLUMN trailer.trail_load_cap IS
    'trailer load capacity (in kg)';

COMMENT ON COLUMN trailer.trail_purch_date IS
    'Trailer purchase date time';

COMMENT ON COLUMN trailer.trail_cost IS
    'trailier cost';

COMMENT ON COLUMN trailer.trail_len IS
    'trailer length (in m)';

COMMENT ON COLUMN trailer.trail_model IS
    'trailer model';

COMMENT ON COLUMN trailer.trail_manufacturer IS
    'trailer make';

ALTER TABLE trailer ADD CONSTRAINT trailer_pk PRIMARY KEY ( trail_code );

CREATE TABLE trailer_class (
    trailer_c_name       VARCHAR2(15) NOT NULL,
    trailer_c_daily_rate NUMBER(3) NOT NULL
);

COMMENT ON COLUMN trailer_class.trailer_c_name IS
    'trailer class name';

COMMENT ON COLUMN trailer_class.trailer_c_daily_rate IS
    'trailer daily hire rate';

ALTER TABLE trailer_class ADD CONSTRAINT trail_class_pk PRIMARY KEY ( trailer_c_name );

CREATE TABLE trailer_type (
    trail_model        VARCHAR2(30) NOT NULL,
    trail_manufacturer VARCHAR2(30) NOT NULL,
    trailer_c_name     VARCHAR2(15) NOT NULL
);

COMMENT ON COLUMN trailer_type.trail_model IS
    'trailer model';

COMMENT ON COLUMN trailer_type.trail_manufacturer IS
    'trailer make';

COMMENT ON COLUMN trailer_type.trailer_c_name IS
    'trailer class name';

ALTER TABLE trailer_type ADD CONSTRAINT trailer_class_pk PRIMARY KEY ( trail_model,
                                                                       trail_manufacturer );

CREATE TABLE truck (
    truck_vin               CHAR(17) NOT NULL,
    truck_rego              CHAR(9) NOT NULL,
    truck_mileage           NUMBER(8, 2) NOT NULL,
    truck_mileage_last_serv NUMBER(7, 2) NOT NULL,
    truck_purch_date        DATE NOT NULL,
    truck_cost              NUMBER(8, 2) NOT NULL,
    truck_make              VARCHAR2(30) NOT NULL,
    truck_model             VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN truck.truck_vin IS
    'truck VIN';

COMMENT ON COLUMN truck.truck_rego IS
    'truck registration number';

COMMENT ON COLUMN truck.truck_mileage IS
    'truck mileage';

COMMENT ON COLUMN truck.truck_mileage_last_serv IS
    'truck mileage last serviced';

COMMENT ON COLUMN truck.truck_purch_date IS
    'truck purchase date';

COMMENT ON COLUMN truck.truck_cost IS
    'truck cost';

COMMENT ON COLUMN truck.truck_make IS
    'truck_make';

COMMENT ON COLUMN truck.truck_model IS
    'truck model';

ALTER TABLE truck ADD CONSTRAINT truck_pk PRIMARY KEY ( truck_vin );

CREATE TABLE truck_class (
    truck_class_name       VARCHAR2(15) NOT NULL,
    truck_driver_hire_rate NUMBER(3) NOT NULL,
    truck_daily_hire_rate  NUMBER(3) NOT NULL
);

ALTER TABLE truck_class
    ADD CONSTRAINT chk_truck_type CHECK ( truck_class_name IN ( '1', '2', '3', '4', '5' ) );

COMMENT ON COLUMN truck_class.truck_class_name IS
    'truck class name';

COMMENT ON COLUMN truck_class.truck_driver_hire_rate IS
    'truck driver hire rate';

COMMENT ON COLUMN truck_class.truck_daily_hire_rate IS
    'truck daily hire rate';

ALTER TABLE truck_class ADD CONSTRAINT truck_class_pk PRIMARY KEY ( truck_class_name );

CREATE TABLE truck_trail_combo (
    truck_trail_no CHAR(5) NOT NULL,
    combo_code     CHAR(3) NOT NULL,
    purpose_no     CHAR(3) NOT NULL,
    trail_code     CHAR(5) NOT NULL,
    truck_vin      CHAR(17) NOT NULL
);

COMMENT ON COLUMN truck_trail_combo.truck_trail_no IS
    'surrogate key for TRUCK_TRAIL_COMBO';

COMMENT ON COLUMN truck_trail_combo.combo_code IS
    'truck and trailer combination code';

COMMENT ON COLUMN truck_trail_combo.purpose_no IS
    'purpose number';

COMMENT ON COLUMN truck_trail_combo.trail_code IS
    'trailer code';

COMMENT ON COLUMN truck_trail_combo.truck_vin IS
    'truck VIN';

ALTER TABLE truck_trail_combo ADD CONSTRAINT truck_trail_combo_pk PRIMARY KEY ( truck_trail_no );

ALTER TABLE truck_trail_combo ADD CONSTRAINT truck_trail_combo_nk UNIQUE ( purpose_no,
                                                                           combo_code );

CREATE TABLE truck_type (
    truck_make       VARCHAR2(30) NOT NULL,
    truck_model      VARCHAR2(30) NOT NULL,
    truck_class_name VARCHAR2(15) NOT NULL
);

COMMENT ON COLUMN truck_type.truck_make IS
    'truck_make';

COMMENT ON COLUMN truck_type.truck_model IS
    'truck model';

COMMENT ON COLUMN truck_type.truck_class_name IS
    'truck class name';

ALTER TABLE truck_type ADD CONSTRAINT truck_type_pk PRIMARY KEY ( truck_make,
                                                                  truck_model );

ALTER TABLE quote
    ADD CONSTRAINT customer_quote FOREIGN KEY ( cust_no )
        REFERENCES customer ( cust_no );

ALTER TABLE employee
    ADD CONSTRAINT employee FOREIGN KEY ( emp_no1 )
        REFERENCES employee ( emp_no );

ALTER TABLE job
    ADD CONSTRAINT employee_job FOREIGN KEY ( emp_no )
        REFERENCES employee ( emp_no );

ALTER TABLE job
    ADD CONSTRAINT employee_job2 FOREIGN KEY ( emp_no1 )
        REFERENCES employee ( emp_no );

ALTER TABLE quote
    ADD CONSTRAINT employee_quote FOREIGN KEY ( emp_no )
        REFERENCES employee ( emp_no );

ALTER TABLE truck_trail_combo
    ADD CONSTRAINT purpose_trucktrailcombo FOREIGN KEY ( purpose_no )
        REFERENCES purpose ( purpose_no );

ALTER TABLE job
    ADD CONSTRAINT quote_job FOREIGN KEY ( quote_no )
        REFERENCES quote ( quote_no );

ALTER TABLE truck_trail_combo
    ADD CONSTRAINT trailer_trucktrailcombo FOREIGN KEY ( trail_code )
        REFERENCES trailer ( trail_code );

ALTER TABLE trailer_type
    ADD CONSTRAINT trailerclass_trailertype FOREIGN KEY ( trailer_c_name )
        REFERENCES trailer_class ( trailer_c_name );

ALTER TABLE truck_trail_combo
    ADD CONSTRAINT truck_trucktrailcombo FOREIGN KEY ( truck_vin )
        REFERENCES truck ( truck_vin );

ALTER TABLE truck_type
    ADD CONSTRAINT truckclass_trucktype FOREIGN KEY ( truck_class_name )
        REFERENCES truck_class ( truck_class_name );

ALTER TABLE job
    ADD CONSTRAINT trucktrailcombo_job FOREIGN KEY ( truck_trail_no )
        REFERENCES truck_trail_combo ( truck_trail_no );

ALTER TABLE trailer
    ADD CONSTRAINT trucktype_trailer FOREIGN KEY ( trail_model,
                                                   trail_manufacturer )
        REFERENCES trailer_type ( trail_model,
                                  trail_manufacturer );

ALTER TABLE truck
    ADD CONSTRAINT trucktype_truck FOREIGN KEY ( truck_make,
                                                 truck_model )
        REFERENCES truck_type ( truck_make,
                                truck_model );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             1
-- ALTER TABLE                             34
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL OFF
SET ECHO OFF